SUCCESS = 0
FAILED = 1
ERROR = 1
IGNORE_MSG = 2
DUP_REQUEST = 3
NOT_FOUND = 4
NO_MSG_READY = 5
BAD_REQ = 9

HTTP_SUCCESS = 200
HTTP_CREATED = 201
HTTP_NO_CONTENT = 204
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409
HTTP_INTERNAL_ERR = 500

def herror(rc):
    
    if rc in (SUCCESS, IGNORE_MSG, DUP_REQUEST):
        return HTTP_SUCCESS 
    if rc == NOT_FOUND:
        return HTTP_NOT_FOUND
    if rc == NO_MSG_READY:
        return  HTTP_NO_CONTENT
    if rc  == BAD_REQ:
        return HTTP_BAD_REQUEST
         
    return HTTP_INTERNAL_ERR
    
